[package]
name = "dprint-plugin-typescript"
description = "TypeScript code formatting plugin for Dprint."
keywords = ["formatting", "formatter", "typescript"]
version = "0.25.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/dprint/dprint-plugin-typescript"
repository = "https://github.com/dprint/dprint-plugin-typescript"

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"

[features]
wasm = []

[dependencies]
dprint-core = "0.24.1"
swc_common = "=0.8.0"
swc_ecmascript = { version = "=0.1.0", features = ["parser"] }
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
dprint-development = "0.2.2"
debug-here = "0.2"
